# Generated by Django 3.0.8 on 2020-08-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_type', models.CharField(max_length=50)),
                ('track_name', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
            ],
        ),
    ]
