# Generated by Django 3.0.8 on 2020-08-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='track',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='track',
            name='group',
        ),
        migrations.RemoveField(
            model_name='track',
            name='label',
        ),
        migrations.RemoveField(
            model_name='track',
            name='track_id',
        ),
        migrations.AddField(
            model_name='track',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
