# Generated by Django 3.0.8 on 2020-08-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_auto_20200802_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='id',
        ),
        migrations.AlterField(
            model_name='track',
            name='track_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
